import rewards
import re
import json


# -*- coding: utf-8 -*-
"""gpt-oss-(20B)-Fine-tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/gpt-oss-(20B)-Fine-tuning.ipynb

To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your own computer, follow the installation instructions on our Github page [here](https://docs.unsloth.ai/get-started/installing-+-updating).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & [how to save it](#Save)

### News

Introducing Unsloth [Standby for RL](https://docs.unsloth.ai/basics/memory-efficient-rl): GRPO is now faster, uses 30% less memory with 2x longer context.

Gpt-oss fine-tuning now supports 8× longer context with 0 accuracy loss. [Read more](https://docs.unsloth.ai/basics/long-context-gpt-oss-training)

Unsloth now supports Text-to-Speech (TTS) models. Read our [guide here](https://docs.unsloth.ai/basics/text-to-speech-tts-fine-tuning).

Visit our docs for all our [model uploads](https://docs.unsloth.ai/get-started/all-our-models) and [notebooks](https://docs.unsloth.ai/get-started/unsloth-notebooks).

### Installation
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# # We're installing the latest Torch, Triton, OpenAI's Triton kernels, Transformers and Unsloth!
# !pip install --upgrade -qqq uv
# try: import numpy; get_numpy = f"numpy=={numpy.__version__}"
# except: get_numpy = "numpy"
# !uv pip install -qqq \
#     "torch>=2.8.0" "triton>=3.4.0" {get_numpy} torchvision bitsandbytes "transformers>=4.55.3" \
#     "unsloth_zoo[base] @ git+https://github.com/unslothai/unsloth-zoo" \
#     "unsloth[base] @ git+https://github.com/unslothai/unsloth" \
#     git+https://github.com/triton-lang/triton.git@05b2c186c1b6c9a08375389d5efe9cb4c401c075#subdirectory=python/triton_kernels
# !uv pip install transformers==4.55.4
# !uv pip install --no-deps trl==0.22.2

"""### Unsloth

We're about to demonstrate the power of the new OpenAI GPT-OSS 20B model through a finetuning example. To use our `MXFP4` inference example, use this [notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/GPT_OSS_MXFP4_(20B)-Inference.ipynb) instead.
"""

from unsloth import FastLanguageModel
import torch
max_seq_length = 1024
dtype = None

# 4bit pre quantized models we support for 4x faster downloading + no OOMs.
fourbit_models = [
    "unsloth/gpt-oss-20b-unsloth-bnb-4bit", # 20B model using bitsandbytes 4bit quantization
    "unsloth/gpt-oss-120b-unsloth-bnb-4bit",
    "unsloth/gpt-oss-20b", # 20B model using MXFP4 format
    "unsloth/gpt-oss-120b",
] # More models at https://huggingface.co/unsloth

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/gpt-oss-20b",
    dtype = dtype, # None for auto detection
    max_seq_length = max_seq_length, # Choose any for long context!
    load_in_4bit = True,  # 4 bit quantization to reduce memory
    full_finetuning = False, # [NEW!] We have full finetuning now!
    # token = "hf_...", # use one if using gated models
)

"""We now add LoRA adapters for parameter efficient finetuning - this allows us to only efficiently train 1% of all parameters."""

model = FastLanguageModel.get_peft_model(
    model,
    r = 4, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 4,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

model.config.use_cache = False

"""### Reasoning Effort
The `gpt-oss` models from OpenAI include a feature that allows users to adjust the model's "reasoning effort." This gives you control over the trade-off between the model's performance and its response speed (latency) which by the amount of token the model will use to think.

----

The `gpt-oss` models offer three distinct levels of reasoning effort you can choose from:

* **Low**: Optimized for tasks that need very fast responses and don't require complex, multi-step reasoning.
* **Medium**: A balance between performance and speed.
* **High**: Provides the strongest reasoning performance for tasks that require it, though this results in higher latency.
"""

from transformers import TextStreamer

# messages = [
#     {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
# ]
# inputs = tokenizer.apply_chat_template(
#     messages,
#     add_generation_prompt = True,
#     return_tensors = "pt",
#     return_dict = True,
#     reasoning_effort = "low", # **NEW!** Set reasoning effort to low, medium or high
# ).to(model.device)

# _ = model.generate(**inputs, max_new_tokens = 64, streamer = TextStreamer(tokenizer))

# """Changing the `reasoning_effort` to `medium` will make the model think longer. We have to increase the `max_new_tokens` to occupy the amount of the generated tokens but it will give better and more correct answer"""

# from transformers import TextStreamer

# messages = [
#     {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
# ]
# inputs = tokenizer.apply_chat_template(
#     messages,
#     add_generation_prompt = True,
#     return_tensors = "pt",
#     return_dict = True,
#     reasoning_effort = "medium", # **NEW!** Set reasoning effort to low, medium or high
# ).to(model.device)

# _ = model.generate(**inputs, max_new_tokens = 64, streamer = TextStreamer(tokenizer))

# """Lastly we will test it using `reasoning_effort` to `high`"""

# from transformers import TextStreamer

# messages = [
#     {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
# ]
# inputs = tokenizer.apply_chat_template(
#     messages,
#     add_generation_prompt = True,
#     return_tensors = "pt",
#     return_dict = True,
#     reasoning_effort = "high", # **NEW!** Set reasoning effort to low, medium or high
# ).to(model.device)

# _ = model.generate(**inputs, max_new_tokens = 64, streamer = TextStreamer(tokenizer))

"""<a name="Data"></a>
### Data Prep

The `HuggingFaceH4/Multilingual-Thinking` dataset will be utilized as our example. This dataset, available on Hugging Face, contains reasoning chain-of-thought examples derived from user questions that have been translated from English into four other languages. It is also the same dataset referenced in OpenAI's [cookbook](https://cookbook.openai.com/articles/gpt-oss/fine-tune-transfomers) for fine-tuning. The purpose of using this dataset is to enable the model to learn and develop reasoning capabilities in these four distinct languages.
"""
import re, json
import rewards  # your helper module

def compute_reward(prompts, completions, completion_ids, **reward_kwargs):
    """Compute GRPO reward given model completion and expert reference (both formatted)."""

    def extract_block(text, tag):
        match = re.search(fr"<{tag}>(.*?)</{tag}>", text, re.S)
        return match.group(1).strip() if match else ""

    def safe_json(text):
        try:
            return json.loads(text)
        except Exception:
            return []

    reward_values = []
    print(f"kwargs: {reward_kwargs}")
    print(f"completions : {completions}")
    experts = reward_kwargs["response"]
    print(f"experts : {experts}")
    for completion, expert, context in zip(completions, experts, reward_kwargs["context"]):
        try:
            # Parse model output
            reasoning_out = extract_block(completion, "reasoning")
            traj_out = safe_json(extract_block(completion, "trajectory"))
            weights_out = safe_json(extract_block(completion, "weights"))

            # Parse expert
            reasoning_exp = extract_block(expert, "reasoning")
            traj_exp = safe_json(extract_block(expert, "trajectory"))
            weights_exp = safe_json(extract_block(expert, "weights"))
        except Exception as e:
            raise ValueError(f"[RewardParseError] {e}")

        # Sub-rewards
        r_format = rewards.format_reward(completion)
        r_bounds = rewards.bounds_reward(
            traj_out, weights_out,
            reward_kwargs["bounds_min"][0], reward_kwargs["bounds_max"][0]
        )
        r_traj = rewards.trajectory_reward(traj_exp, traj_out)
        r_weights = rewards.weights_reward(weights_exp, weights_out)
        r_reasoning = rewards.reasoning_reward(reasoning_out, context["states"])

        # Weighted sum
        total = (
            0.3 * r_format +
            0.3 * r_bounds +
            0.2 * r_traj +
            0.1 * r_weights +
            0.1 * r_reasoning
        )
        reward_values.append(total)

    return reward_values



def generate_system_prompt(context, states, max, min, current_state):
    return f"""
{context}

TASK
Generate a minimal, sufficient **trajectory** of target states and a matching 2D array of per-variable **weights** for the given command.

DEFINITIONS
States: {states}
Bounds: min = {min}, max = {max}
Current state: {current_state}

STRICT OUTPUT SPEC (MUST FOLLOW EXACTLY)
- If the instruction is ambiguous or any required info is missing, output **only**:
  <clarification>clear_text_explaining_what_is_missing_or_ambiguous</clarification>
  (No other text allowed.)

- Otherwise output **exactly these three tags in this order** and nothing else:
  1) <reasoning>...</reasoning>
     - Free text explaining assumptions and why each target state & weighting was chosen.
     - How this trajectory meets the user's request
     - Keep it concise (max ~6 short sentences).
  2) <trajectory>[[...],[...],...]</trajectory>
     - A 2D JSON array (list of rows) of numeric **floats** only.
     - Each row = one target state; each column corresponds to the state variables listed above.
     - Use decimal notation (e.g. 0.125 or 1.0). **Do not** use scientific notation (`1e-3`), expressions, variable names, comments, or trailing commas.
  3) <weights>[[...],[...],...]</weights>
     - A 2D JSON array of floats with **exactly the same shape** as `<trajectory>`.
     - Every element must be in range [0.0, 1.0].
     - Weights are the importance per state variable in the target state not the state itself. These can change at different target states.
     - No extra text or formatting.

VALIDATION STEPS (you must perform these checks before returning)
1. Shape: number of columns in each `<trajectory>` row == number of state variables in `States`. Number of rows in `<weights>` == number of rows in `<trajectory>`. Each corresponding row length must match.
2. Bounds: every trajectory value must satisfy `min <= value <= max` for the corresponding state variable.
3. Weights: every weight must satisfy `0.0 <= weight <= 1.0`.
4. Formatting: `<trajectory>` and `<weights>` must be valid JSON arrays containing only numeric literals (no comments, no text).
If any check fails, **do not** output reasoning or arrays — output **only** a `<clarification>` tag listing the failing checks (short, comma-separated).

ADDITIONAL RULES
- Do not include any other tags or text outside the tags described above.
- Do not guess: if you must assume something to proceed, stop and request clarification using `<clarification>`.
- Include the current state as the first entry in the trajectory

EXAMPLE (format only — replace with real numbers that respect bounds and shapes)
<reasoning>Concise reason for states and weights.</reasoning>
<trajectory>[[0.0, 1.0, 0.5], [0.2, 0.9, 0.1]]</trajectory>
<weights>[[1.0, 0.8, 0.2], [0.9, 0.7, 0.1]]</weights>

Now produce the output for the command that follows.
"""

def format_output(reasoning, trajectory, weights):
    return f'''<reasoning>{reasoning}</reasoning>
<trajectory>{trajectory}</trajectory>
<weights>{weights}</weights>
'''


def formatting_prompts_func(examples):
    instruction = examples["instruction"]
    system = examples["system"]
    states = examples["states"]
    maxv = examples["bounds_max"]
    minv = examples["bounds_min"]
    reasoning = examples["reasoning"]
    trajectory = examples["trajectory"]
    weights = examples["weights"]

    prompts, responses = [], []

    for i in range(len(instruction)):
        # build system/user/assistant messages
        cs_i = trajectory[i].find("]")
        cs = trajectory[i][1:cs_i + 1]
        convo = [
            {"role": "system", "content": generate_system_prompt(system[i], states[i], maxv[i], minv[i], cs)},
            {"role": "user", "content": instruction[i]},
        ]
        prompt_text = tokenizer.apply_chat_template(convo, tokenize=False, add_generation_prompt=True, reasoning_effort = "low")
        response_text = format_output(reasoning[i], trajectory[i], weights[i])
        prompts.append(prompt_text)
        responses.append(response_text)

    return {
        "prompt": prompts,
        "response": responses,
    }


def flatten_data(example):
    c, o = example["context"], example["output"]
    return {
        "instruction": example["instruction"],
        "system": c["system"],
        "states": json.dumps(c["states"]),
        "bounds_min": c["bounds"]["min"],
        "bounds_max": c["bounds"]["max"],
        "reasoning": o["reasoning"],
        "trajectory": json.dumps(o["trajectory"]),   # already a string
        "weights": json.dumps(o["weights"]),         # already a string
    }

def formatting_prompts_func_(examples):
    convos = examples["messages"]
    print(convos[0])
    exit()
    texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False) for convo in convos]
    print(texts[0])
    exit()
    return { "text" : texts, }
pass

from datasets import load_dataset

# dataset = load_dataset("HuggingFaceH4/Multilingual-Thinking", split="train")
dataset = load_dataset("json", data_files="gpt_dataset.json", split="train")

"""To format our dataset, we will apply our version of the GPT OSS prompt"""

from unsloth.chat_templates import standardize_sharegpt
# dataset = standardize_sharegpt(dataset)
dataset = dataset.map(flatten_data)
dataset = dataset.map(formatting_prompts_func, batched = True,)

"""Let's take a look at the dataset, and check what the 1st example shows"""

# print(dataset[0]['text'])

"""What is unique about GPT-OSS is that it uses OpenAI [Harmony](https://github.com/openai/harmony) format which support conversation structures, reasoning output, and tool calling.

<a name="Train"></a>
### Train the model
Now let's train our model. We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`.
"""

from trl import SFTConfig, SFTTrainer
from trl import GRPOTrainer, GRPOConfig
# trainer = GRPOTrainer(
#     model = model,
#     tokenizer = tokenizer,
#     train_dataset = dataset,
#     reward_funcs = compute_reward,
#     args = GRPOConfig(
#         max_completion_length=max_seq_length,
#         per_device_train_batch_size = 1,
#         gradient_accumulation_steps = 4,
#         warmup_steps = 5,
#         num_train_epochs = 1,        # same as before
#         learning_rate = 2e-4,
#         logging_steps = 1,
#         optim = "adamw_8bit",
#         weight_decay = 0.01,
#         lr_scheduler_type = "linear",
#         seed = 3407,
#         output_dir = "outputs",
#         report_to = "none",          # same as before
#     ),
# )
maximum_length = 1024
max_prompt_length     = maximum_length + 1
max_completion_length = 2048 - max_prompt_length

training_args = GRPOConfig(
    temperature=1.0,
    learning_rate=5e-5,
    weight_decay=0.01,
    warmup_ratio=0.1,
    lr_scheduler_type="linear",
    optim="adamw_8bit",
    logging_steps=1,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=1,    # bump to 4 for smoother reward signals
    num_generations=2,                # lower if you OOM
    max_prompt_length=max_prompt_length,
    max_completion_length=max_completion_length,
    # max_steps=1000,                   # or set num_train_epochs=1
    num_train_epochs=1,
    save_steps=100,
    report_to="none",
    output_dir="outputs"
)

trainer = GRPOTrainer(
    model=model,
    processing_class=tokenizer,
    reward_funcs=compute_reward,
    args=training_args,
    train_dataset=dataset,
    # Optional eval split:
    # train_dataset=new_dataset["train"],
    # eval_dataset=new_dataset["test"],
)

# @title Show current memory stats
gpu_stats = torch.cuda.get_device_properties(0)
start_gpu_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
max_memory = round(gpu_stats.total_memory / 1024 / 1024 / 1024, 3)
print(f"GPU = {gpu_stats.name}. Max memory = {max_memory} GB.")
print(f"{start_gpu_memory} GB of memory reserved.")

trainer_stats = trainer.train()

# @title Show final memory and time stats
used_memory = round(torch.cuda.max_memory_reserved() / 1024 / 1024 / 1024, 3)
used_memory_for_lora = round(used_memory - start_gpu_memory, 3)
used_percentage = round(used_memory / max_memory * 100, 3)
lora_percentage = round(used_memory_for_lora / max_memory * 100, 3)
print(f"{trainer_stats.metrics['train_runtime']} seconds used for training.")
print(
    f"{round(trainer_stats.metrics['train_runtime']/60, 2)} minutes used for training."
)
print(f"Peak reserved memory = {used_memory} GB.")
print(f"Peak reserved memory for training = {used_memory_for_lora} GB.")
print(f"Peak reserved memory % of max memory = {used_percentage} %.")
print(f"Peak reserved memory for training % of max memory = {lora_percentage} %.")

"""<a name="Inference"></a>
### Inference
Let's run the model! You can change the instruction and input - leave the output blank!
"""

# messages = [
#     {"role": "system", "content": "reasoning language: French\n\nYou are a helpful assistant that can solve mathematical problems."},
#     {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
# ]
# inputs = tokenizer.apply_chat_template(
#     messages,
#     add_generation_prompt = True,
#     return_tensors = "pt",
#     return_dict = True,
#     reasoning_effort = "medium",
# ).to(model.device)
# from transformers import TextStreamer
# _ = model.generate(**inputs, max_new_tokens = 64, streamer = TextStreamer(tokenizer))

# """<a name="Save"></a>
# ### Saving, loading finetuned models
# To save the final model as LoRA adapters, either use Huggingface's `push_to_hub` for an online save or `save_pretrained` for a local save.

# **[NOTE]** Currently finetunes can only be loaded via Unsloth in the meantime - we're working on vLLM and GGUF exporting!
# """

model.save_pretrained("planning_model")
# model.push_to_hub("hf_username/finetuned_model", token = "hf_...") # Save to HF

"""To run the finetuned model, you can do the below after setting `if False` to `if True` in a new instance."""

if False:
    from unsloth import FastLanguageModel
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "finetuned_model", # YOUR MODEL YOU USED FOR TRAINING
        max_seq_length = 1024,
        dtype = None,
        load_in_4bit = True,
    )

messages = [
    {"role": "system", "content": "reasoning language: French\n\nYou are a helpful assistant that can solve mathematical problems."},
    {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
    return_dict = True,
    reasoning_effort = "high",
).to(model.device)
from transformers import TextStreamer
_ = model.generate(**inputs, max_new_tokens = 64, streamer = TextStreamer(tokenizer))

"""And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other links:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
6. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://docs.unsloth.ai/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

"""