# -*- coding: utf-8 -*-
"""gpt-oss-(20B)-Fine-tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/gpt-oss-(20B)-Fine-tuning.ipynb

To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your own computer, follow the installation instructions on our Github page [here](https://docs.unsloth.ai/get-started/installing-+-updating).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & [how to save it](#Save)

### News

Introducing Unsloth [Standby for RL](https://docs.unsloth.ai/basics/memory-efficient-rl): GRPO is now faster, uses 30% less memory with 2x longer context.

Gpt-oss fine-tuning now supports 8× longer context with 0 accuracy loss. [Read more](https://docs.unsloth.ai/basics/long-context-gpt-oss-training)

Unsloth now supports Text-to-Speech (TTS) models. Read our [guide here](https://docs.unsloth.ai/basics/text-to-speech-tts-fine-tuning).

Visit our docs for all our [model uploads](https://docs.unsloth.ai/get-started/all-our-models) and [notebooks](https://docs.unsloth.ai/get-started/unsloth-notebooks).

### Installation
"""

# Commented out IPython magic to ensure Python compatibility.
# %%capture
# # We're installing the latest Torch, Triton, OpenAI's Triton kernels, Transformers and Unsloth!
# !pip install --upgrade -qqq uv
# try: import numpy; get_numpy = f"numpy=={numpy.__version__}"
# except: get_numpy = "numpy"
# !uv pip install -qqq \
#     "torch>=2.8.0" "triton>=3.4.0" {get_numpy} torchvision bitsandbytes "transformers>=4.55.3" \
#     "unsloth_zoo[base] @ git+https://github.com/unslothai/unsloth-zoo" \
#     "unsloth[base] @ git+https://github.com/unslothai/unsloth" \
#     git+https://github.com/triton-lang/triton.git@05b2c186c1b6c9a08375389d5efe9cb4c401c075#subdirectory=python/triton_kernels
# !uv pip install transformers==4.55.4
# !uv pip install --no-deps trl==0.22.2

"""### Unsloth

We're about to demonstrate the power of the new OpenAI GPT-OSS 20B model through a finetuning example. To use our `MXFP4` inference example, use this [notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/GPT_OSS_MXFP4_(20B)-Inference.ipynb) instead.
"""

from unsloth import FastLanguageModel
from json import load

with open('config/config.json', 'r') as file:
    config = load(file)

max_seq_length = 1024
dtype = None

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/gpt-oss-20b",
    dtype = dtype, # None for auto detection
    max_seq_length = 2048, # Choose any for long context!
    load_in_4bit = True,  # 4 bit quantization to reduce memory
    
    # full_finetuning = False, # [NEW!] We have full finetuning now!
    # token = "hf_...", # use one if using gated models
)

system_prompt = f'''{config.get("context")}.
Give a trajectory of states and weights for the following command.
The trajectory must have sufficient although minimal target states to capture the complete expected behaviour. The states do not need to be over a complete time sequence, but just represent targets.
Each variable in each target state must have a weight value between 0 an 1 depending on how important the variable is to obtain the desired user behaviour. IMPORTANT: This is not the significance of the whole state, but each variable within the state and will often change throughout the trajectory.
The states are {config.get("states")} with max and min values of {config.get("bounds").get("max")} and {config.get("bounds").get("min")}. Do not exceed these bounds.
Reasoning should be given for each state and weighting and be presented in the <reasoning> </reasoning> tags.
Trajectory should be given in the <trajectory></trajectory> tags and be presented as a 2d array of states.
Weights should be given in the <weights></weights> tags and be presented as a 2d array of weights. There must be as many weights as states in the trajectory.
The order should be <reasoning>, <trajectory>, <weights>
The <weights> and <trajectory> should only be a 2d array, no commentsThe current state is {config.get("current_state")}. You may need to move to an appropriate starting state before beginning the command.
VERY IMPORTANT: If the instruction is too vague or anytime you feel you need to make an assumption, simply stop and output only <clarification> clarification_message </clarification> for the user to clarify certain aspects.
DO NOT GUESS ANYTHING
I will present the instructions as line by line commands.
'''

user_command = input("Enter a command for the LLM:\n")

messages = [
    {"role": "system", "content": f"{system_prompt}"},
    {"role": "user", "content": f"{user_command}"},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = False,
    return_tensors = "pt",
    return_dict = True,
    reasoning_effort = "medium",
).to(model.device)
from transformers import TextStreamer
_ = model.generate(**inputs, max_new_tokens = 2048, streamer = TextStreamer(tokenizer))

"""And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other links:
1. Train your own reasoning model - Llama GRPO notebook [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.1_(8B)-GRPO.ipynb)
2. Saving finetunes to Ollama. [Free notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)
3. Llama 3.2 Vision finetuning - Radiography use case. [Free Colab](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3.2_(11B)-Vision.ipynb)
6. See notebooks for DPO, ORPO, Continued pretraining, conversational finetuning and more on our [documentation](https://docs.unsloth.ai/get-started/unsloth-notebooks)!

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://docs.unsloth.ai/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️
</div>

"""